#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


#include <stdbool.h>                            /* bool */
#include <stdint.h>                             /* uintxx_t */
#include <stdio.h>                              /* printf, sprintf */
#include <stdarg.h>
// #include <stdlib.h>
#include <sys/socket.h>                         /* AF_INET[6] */
#include <netinet/in.h>                         /* struct in[6]_addr */
#include <arpa/inet.h>                         /* inet_pton */

#include <libipset/linux_ip_set.h>              /* enum ipset_cmd */
#include <libipset/data.h>    /* enum ipset_data */
#include <libipset/errcode.h>    /* error handling */
#include <libipset/session.h>
#include <libipset/parse.h>   /* ipset_parse_* */
#include <libipset/types.h>   /* struct ipset_type */
#include <libipset/ui.h>    /* core options, commands */
#include <libipset/utils.h>   /* STREQ */

/* Report and output buffer sizes */
#define IPSET_ERRORBUFLEN               1024
#define IPSET_OUTBUFLEN                 8192

static int out_buffer(char *buff);

static int out_fn(char *format, ...) {
    va_list argp;
    char *s;
    va_start(argp, format);
    s = va_arg(argp, char *);
    va_end(argp);
    out_buffer(s);
    return 0;
};    


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 94), // _Bool()(struct ipset_session *, enum ipset_envopt)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 106), // struct ipset_session *
/*  2 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // enum ipset_envopt
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION, 14), // char const *()(struct ipset_session const *)
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 106), // struct ipset_session const *
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(char *)
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 95), // char *
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(char *, ...)
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 1),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(char const *, ...)
/* 14 */ _CFFI_OP(_CFFI_OP_POINTER, 95), // char const *
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 1),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(int, char const *, void *)
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 119), // void *
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_data *, enum ipset_opt, void const *)
/* 22 */ _CFFI_OP(_CFFI_OP_POINTER, 102), // struct ipset_data *
/* 23 */ _CFFI_OP(_CFFI_OP_ENUM, 4), // enum ipset_opt
/* 24 */ _CFFI_OP(_CFFI_OP_POINTER, 119), // void const *
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *)
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, enum ipset_cmd, int)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 31 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // enum ipset_cmd
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, enum ipset_cmd, uint32_t)
/* 35 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 31),
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 38 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, enum ipset_err_type, char const *, ...)
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 41 */ _CFFI_OP(_CFFI_OP_ENUM, 3), // enum ipset_err_type
/* 42 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 1),
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, enum ipset_opt, char const *)
/* 45 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 46 */ _CFFI_OP(_CFFI_OP_NOOP, 23),
/* 47 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 49 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, enum ipset_output_mode)
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 51 */ _CFFI_OP(_CFFI_OP_ENUM, 5), // enum ipset_output_mode
/* 52 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 53 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, int(*)(char const *, ...))
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 55 */ _CFFI_OP(_CFFI_OP_POINTER, 13), // int(*)(char const *, ...)
/* 56 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 57 */ _CFFI_OP(_CFFI_OP_FUNCTION, 17), // int()(struct ipset_session *, int, char const *)
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 59 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 60 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 61 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 62 */ _CFFI_OP(_CFFI_OP_FUNCTION, 22), // struct ipset_data *()(struct ipset_session const *)
/* 63 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 64 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 65 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // struct ipset_handle *()(struct ipset_session const *)
/* 66 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 68 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // struct ipset_session *()(int(*)(char const *, ...))
/* 69 */ _CFFI_OP(_CFFI_OP_NOOP, 55),
/* 70 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 71 */ _CFFI_OP(_CFFI_OP_FUNCTION, 107), // struct ipset_type const *()(struct ipset_session *)
/* 72 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 73 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 74 */ _CFFI_OP(_CFFI_OP_FUNCTION, 107), // struct ipset_type const *()(struct ipset_session *, enum ipset_cmd)
/* 75 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 76 */ _CFFI_OP(_CFFI_OP_NOOP, 31),
/* 77 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 78 */ _CFFI_OP(_CFFI_OP_FUNCTION, 107), // struct ipset_type const *()(struct ipset_session const *)
/* 79 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 80 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 81 */ _CFFI_OP(_CFFI_OP_FUNCTION, 24), // void const *()(struct ipset_data const *, enum ipset_opt)
/* 82 */ _CFFI_OP(_CFFI_OP_POINTER, 102), // struct ipset_data const *
/* 83 */ _CFFI_OP(_CFFI_OP_NOOP, 23),
/* 84 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 85 */ _CFFI_OP(_CFFI_OP_FUNCTION, 119), // void()(struct ipset_session *)
/* 86 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 87 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 88 */ _CFFI_OP(_CFFI_OP_FUNCTION, 119), // void()(struct ipset_session *, uint32_t)
/* 89 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 90 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 91 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 92 */ _CFFI_OP(_CFFI_OP_FUNCTION, 119), // void()(void)
/* 93 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 94 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 95 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 96 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum $1
/* 97 */ _CFFI_OP(_CFFI_OP_POINTER, 7), // int(*)(char *)
/* 98 */ _CFFI_OP(_CFFI_OP_POINTER, 10), // int(*)(char *, ...)
/* 99 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // int(*)(struct ipset_session *, enum ipset_err_type, char const *, ...)
/* 100 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct in6_addr
/* 101 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // struct in_addr
/* 102 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // struct ipset_data
/* 103 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // struct ipset_errcode_table
/* 104 */ _CFFI_OP(_CFFI_OP_POINTER, 105), // struct ipset_handle *
/* 105 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // struct ipset_handle
/* 106 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // struct ipset_session
/* 107 */ _CFFI_OP(_CFFI_OP_POINTER, 108), // struct ipset_type const *
/* 108 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // struct ipset_type
/* 109 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20), // uint16_t
/* 110 */ _CFFI_OP(_CFFI_OP_ARRAY, 109), // uint16_t[8]
/* 111 */ (_cffi_opcode_t)(8),
/* 112 */ _CFFI_OP(_CFFI_OP_ARRAY, 37), // uint32_t[4]
/* 113 */ (_cffi_opcode_t)(4),
/* 114 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 115 */ _CFFI_OP(_CFFI_OP_ARRAY, 114), // uint8_t[16]
/* 116 */ (_cffi_opcode_t)(16),
/* 117 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // union $2
/* 118 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // union nf_inet_addr
/* 119 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_NFPROTO_UNSPEC(unsigned long long *o)
{
  int n = (NFPROTO_UNSPEC) <= 0;
  *o = (unsigned long long)((NFPROTO_UNSPEC) | 0);  /* check that NFPROTO_UNSPEC is an integer */
  return n;
}

static int _cffi_const_NFPROTO_IPV4(unsigned long long *o)
{
  int n = (NFPROTO_IPV4) <= 0;
  *o = (unsigned long long)((NFPROTO_IPV4) | 0);  /* check that NFPROTO_IPV4 is an integer */
  return n;
}

static int _cffi_const_NFPROTO_ARP(unsigned long long *o)
{
  int n = (NFPROTO_ARP) <= 0;
  *o = (unsigned long long)((NFPROTO_ARP) | 0);  /* check that NFPROTO_ARP is an integer */
  return n;
}

static int _cffi_const_NFPROTO_BRIDGE(unsigned long long *o)
{
  int n = (NFPROTO_BRIDGE) <= 0;
  *o = (unsigned long long)((NFPROTO_BRIDGE) | 0);  /* check that NFPROTO_BRIDGE is an integer */
  return n;
}

static int _cffi_const_NFPROTO_IPV6(unsigned long long *o)
{
  int n = (NFPROTO_IPV6) <= 0;
  *o = (unsigned long long)((NFPROTO_IPV6) | 0);  /* check that NFPROTO_IPV6 is an integer */
  return n;
}

static int _cffi_const_NFPROTO_DECNET(unsigned long long *o)
{
  int n = (NFPROTO_DECNET) <= 0;
  *o = (unsigned long long)((NFPROTO_DECNET) | 0);  /* check that NFPROTO_DECNET is an integer */
  return n;
}

static int _cffi_const_NFPROTO_NUMPROTO(unsigned long long *o)
{
  int n = (NFPROTO_NUMPROTO) <= 0;
  *o = (unsigned long long)((NFPROTO_NUMPROTO) | 0);  /* check that NFPROTO_NUMPROTO is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_NONE(unsigned long long *o)
{
  int n = (IPSET_CMD_NONE) <= 0;
  *o = (unsigned long long)((IPSET_CMD_NONE) | 0);  /* check that IPSET_CMD_NONE is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_PROTOCOL(unsigned long long *o)
{
  int n = (IPSET_CMD_PROTOCOL) <= 0;
  *o = (unsigned long long)((IPSET_CMD_PROTOCOL) | 0);  /* check that IPSET_CMD_PROTOCOL is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_CREATE(unsigned long long *o)
{
  int n = (IPSET_CMD_CREATE) <= 0;
  *o = (unsigned long long)((IPSET_CMD_CREATE) | 0);  /* check that IPSET_CMD_CREATE is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_DESTROY(unsigned long long *o)
{
  int n = (IPSET_CMD_DESTROY) <= 0;
  *o = (unsigned long long)((IPSET_CMD_DESTROY) | 0);  /* check that IPSET_CMD_DESTROY is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_FLUSH(unsigned long long *o)
{
  int n = (IPSET_CMD_FLUSH) <= 0;
  *o = (unsigned long long)((IPSET_CMD_FLUSH) | 0);  /* check that IPSET_CMD_FLUSH is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_RENAME(unsigned long long *o)
{
  int n = (IPSET_CMD_RENAME) <= 0;
  *o = (unsigned long long)((IPSET_CMD_RENAME) | 0);  /* check that IPSET_CMD_RENAME is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_SWAP(unsigned long long *o)
{
  int n = (IPSET_CMD_SWAP) <= 0;
  *o = (unsigned long long)((IPSET_CMD_SWAP) | 0);  /* check that IPSET_CMD_SWAP is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_LIST(unsigned long long *o)
{
  int n = (IPSET_CMD_LIST) <= 0;
  *o = (unsigned long long)((IPSET_CMD_LIST) | 0);  /* check that IPSET_CMD_LIST is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_SAVE(unsigned long long *o)
{
  int n = (IPSET_CMD_SAVE) <= 0;
  *o = (unsigned long long)((IPSET_CMD_SAVE) | 0);  /* check that IPSET_CMD_SAVE is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_ADD(unsigned long long *o)
{
  int n = (IPSET_CMD_ADD) <= 0;
  *o = (unsigned long long)((IPSET_CMD_ADD) | 0);  /* check that IPSET_CMD_ADD is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_DEL(unsigned long long *o)
{
  int n = (IPSET_CMD_DEL) <= 0;
  *o = (unsigned long long)((IPSET_CMD_DEL) | 0);  /* check that IPSET_CMD_DEL is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_TEST(unsigned long long *o)
{
  int n = (IPSET_CMD_TEST) <= 0;
  *o = (unsigned long long)((IPSET_CMD_TEST) | 0);  /* check that IPSET_CMD_TEST is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_HEADER(unsigned long long *o)
{
  int n = (IPSET_CMD_HEADER) <= 0;
  *o = (unsigned long long)((IPSET_CMD_HEADER) | 0);  /* check that IPSET_CMD_HEADER is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_TYPE(unsigned long long *o)
{
  int n = (IPSET_CMD_TYPE) <= 0;
  *o = (unsigned long long)((IPSET_CMD_TYPE) | 0);  /* check that IPSET_CMD_TYPE is an integer */
  return n;
}

static int _cffi_const_IPSET_MSG_MAX(unsigned long long *o)
{
  int n = (IPSET_MSG_MAX) <= 0;
  *o = (unsigned long long)((IPSET_MSG_MAX) | 0);  /* check that IPSET_MSG_MAX is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_RESTORE(unsigned long long *o)
{
  int n = (IPSET_CMD_RESTORE) <= 0;
  *o = (unsigned long long)((IPSET_CMD_RESTORE) | 0);  /* check that IPSET_CMD_RESTORE is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_HELP(unsigned long long *o)
{
  int n = (IPSET_CMD_HELP) <= 0;
  *o = (unsigned long long)((IPSET_CMD_HELP) | 0);  /* check that IPSET_CMD_HELP is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_VERSION(unsigned long long *o)
{
  int n = (IPSET_CMD_VERSION) <= 0;
  *o = (unsigned long long)((IPSET_CMD_VERSION) | 0);  /* check that IPSET_CMD_VERSION is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_QUIT(unsigned long long *o)
{
  int n = (IPSET_CMD_QUIT) <= 0;
  *o = (unsigned long long)((IPSET_CMD_QUIT) | 0);  /* check that IPSET_CMD_QUIT is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_MAX(unsigned long long *o)
{
  int n = (IPSET_CMD_MAX) <= 0;
  *o = (unsigned long long)((IPSET_CMD_MAX) | 0);  /* check that IPSET_CMD_MAX is an integer */
  return n;
}

static int _cffi_const_IPSET_CMD_COMMIT(unsigned long long *o)
{
  int n = (IPSET_CMD_COMMIT) <= 0;
  *o = (unsigned long long)((IPSET_CMD_COMMIT) | 0);  /* check that IPSET_CMD_COMMIT is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_SORTED(unsigned long long *o)
{
  int n = (IPSET_ENV_SORTED) <= 0;
  *o = (unsigned long long)((IPSET_ENV_SORTED) | 0);  /* check that IPSET_ENV_SORTED is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_QUIET(unsigned long long *o)
{
  int n = (IPSET_ENV_QUIET) <= 0;
  *o = (unsigned long long)((IPSET_ENV_QUIET) | 0);  /* check that IPSET_ENV_QUIET is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_RESOLVE(unsigned long long *o)
{
  int n = (IPSET_ENV_RESOLVE) <= 0;
  *o = (unsigned long long)((IPSET_ENV_RESOLVE) | 0);  /* check that IPSET_ENV_RESOLVE is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_EXIST(unsigned long long *o)
{
  int n = (IPSET_ENV_EXIST) <= 0;
  *o = (unsigned long long)((IPSET_ENV_EXIST) | 0);  /* check that IPSET_ENV_EXIST is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_LIST_SETNAME(unsigned long long *o)
{
  int n = (IPSET_ENV_LIST_SETNAME) <= 0;
  *o = (unsigned long long)((IPSET_ENV_LIST_SETNAME) | 0);  /* check that IPSET_ENV_LIST_SETNAME is an integer */
  return n;
}

static int _cffi_const_IPSET_ENV_LIST_HEADER(unsigned long long *o)
{
  int n = (IPSET_ENV_LIST_HEADER) <= 0;
  *o = (unsigned long long)((IPSET_ENV_LIST_HEADER) | 0);  /* check that IPSET_ENV_LIST_HEADER is an integer */
  return n;
}

static int _cffi_const_IPSET_ERROR(unsigned long long *o)
{
  int n = (IPSET_ERROR) <= 0;
  *o = (unsigned long long)((IPSET_ERROR) | 0);  /* check that IPSET_ERROR is an integer */
  return n;
}

static int _cffi_const_IPSET_WARNING(unsigned long long *o)
{
  int n = (IPSET_WARNING) <= 0;
  *o = (unsigned long long)((IPSET_WARNING) | 0);  /* check that IPSET_WARNING is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_NONE(unsigned long long *o)
{
  int n = (IPSET_OPT_NONE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_NONE) | 0);  /* check that IPSET_OPT_NONE is an integer */
  return n;
}

static int _cffi_const_IPSET_SETNAME(unsigned long long *o)
{
  int n = (IPSET_SETNAME) <= 0;
  *o = (unsigned long long)((IPSET_SETNAME) | 0);  /* check that IPSET_SETNAME is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_TYPENAME(unsigned long long *o)
{
  int n = (IPSET_OPT_TYPENAME) <= 0;
  *o = (unsigned long long)((IPSET_OPT_TYPENAME) | 0);  /* check that IPSET_OPT_TYPENAME is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_FAMILY(unsigned long long *o)
{
  int n = (IPSET_OPT_FAMILY) <= 0;
  *o = (unsigned long long)((IPSET_OPT_FAMILY) | 0);  /* check that IPSET_OPT_FAMILY is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IP(unsigned long long *o)
{
  int n = (IPSET_OPT_IP) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IP) | 0);  /* check that IPSET_OPT_IP is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IP_FROM(unsigned long long *o)
{
  int n = (IPSET_OPT_IP_FROM) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IP_FROM) | 0);  /* check that IPSET_OPT_IP_FROM is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IP_TO(unsigned long long *o)
{
  int n = (IPSET_OPT_IP_TO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IP_TO) | 0);  /* check that IPSET_OPT_IP_TO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_CIDR(unsigned long long *o)
{
  int n = (IPSET_OPT_CIDR) <= 0;
  *o = (unsigned long long)((IPSET_OPT_CIDR) | 0);  /* check that IPSET_OPT_CIDR is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_MARK(unsigned long long *o)
{
  int n = (IPSET_OPT_MARK) <= 0;
  *o = (unsigned long long)((IPSET_OPT_MARK) | 0);  /* check that IPSET_OPT_MARK is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PORT(unsigned long long *o)
{
  int n = (IPSET_OPT_PORT) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PORT) | 0);  /* check that IPSET_OPT_PORT is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PORT_FROM(unsigned long long *o)
{
  int n = (IPSET_OPT_PORT_FROM) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PORT_FROM) | 0);  /* check that IPSET_OPT_PORT_FROM is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PORT_TO(unsigned long long *o)
{
  int n = (IPSET_OPT_PORT_TO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PORT_TO) | 0);  /* check that IPSET_OPT_PORT_TO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_TIMEOUT(unsigned long long *o)
{
  int n = (IPSET_OPT_TIMEOUT) <= 0;
  *o = (unsigned long long)((IPSET_OPT_TIMEOUT) | 0);  /* check that IPSET_OPT_TIMEOUT is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_GC(unsigned long long *o)
{
  int n = (IPSET_OPT_GC) <= 0;
  *o = (unsigned long long)((IPSET_OPT_GC) | 0);  /* check that IPSET_OPT_GC is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_HASHSIZE(unsigned long long *o)
{
  int n = (IPSET_OPT_HASHSIZE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_HASHSIZE) | 0);  /* check that IPSET_OPT_HASHSIZE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_MAXELEM(unsigned long long *o)
{
  int n = (IPSET_OPT_MAXELEM) <= 0;
  *o = (unsigned long long)((IPSET_OPT_MAXELEM) | 0);  /* check that IPSET_OPT_MAXELEM is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_MARKMASK(unsigned long long *o)
{
  int n = (IPSET_OPT_MARKMASK) <= 0;
  *o = (unsigned long long)((IPSET_OPT_MARKMASK) | 0);  /* check that IPSET_OPT_MARKMASK is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_NETMASK(unsigned long long *o)
{
  int n = (IPSET_OPT_NETMASK) <= 0;
  *o = (unsigned long long)((IPSET_OPT_NETMASK) | 0);  /* check that IPSET_OPT_NETMASK is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PROBES(unsigned long long *o)
{
  int n = (IPSET_OPT_PROBES) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PROBES) | 0);  /* check that IPSET_OPT_PROBES is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_RESIZE(unsigned long long *o)
{
  int n = (IPSET_OPT_RESIZE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_RESIZE) | 0);  /* check that IPSET_OPT_RESIZE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SIZE(unsigned long long *o)
{
  int n = (IPSET_OPT_SIZE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SIZE) | 0);  /* check that IPSET_OPT_SIZE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_FORCEADD(unsigned long long *o)
{
  int n = (IPSET_OPT_FORCEADD) <= 0;
  *o = (unsigned long long)((IPSET_OPT_FORCEADD) | 0);  /* check that IPSET_OPT_FORCEADD is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_ELEMENTS(unsigned long long *o)
{
  int n = (IPSET_OPT_ELEMENTS) <= 0;
  *o = (unsigned long long)((IPSET_OPT_ELEMENTS) | 0);  /* check that IPSET_OPT_ELEMENTS is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_REFERENCES(unsigned long long *o)
{
  int n = (IPSET_OPT_REFERENCES) <= 0;
  *o = (unsigned long long)((IPSET_OPT_REFERENCES) | 0);  /* check that IPSET_OPT_REFERENCES is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_MEMSIZE(unsigned long long *o)
{
  int n = (IPSET_OPT_MEMSIZE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_MEMSIZE) | 0);  /* check that IPSET_OPT_MEMSIZE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_ETHER(unsigned long long *o)
{
  int n = (IPSET_OPT_ETHER) <= 0;
  *o = (unsigned long long)((IPSET_OPT_ETHER) | 0);  /* check that IPSET_OPT_ETHER is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_NAME(unsigned long long *o)
{
  int n = (IPSET_OPT_NAME) <= 0;
  *o = (unsigned long long)((IPSET_OPT_NAME) | 0);  /* check that IPSET_OPT_NAME is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_NAMEREF(unsigned long long *o)
{
  int n = (IPSET_OPT_NAMEREF) <= 0;
  *o = (unsigned long long)((IPSET_OPT_NAMEREF) | 0);  /* check that IPSET_OPT_NAMEREF is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IP2(unsigned long long *o)
{
  int n = (IPSET_OPT_IP2) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IP2) | 0);  /* check that IPSET_OPT_IP2 is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_CIDR2(unsigned long long *o)
{
  int n = (IPSET_OPT_CIDR2) <= 0;
  *o = (unsigned long long)((IPSET_OPT_CIDR2) | 0);  /* check that IPSET_OPT_CIDR2 is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IP2_TO(unsigned long long *o)
{
  int n = (IPSET_OPT_IP2_TO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IP2_TO) | 0);  /* check that IPSET_OPT_IP2_TO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PROTO(unsigned long long *o)
{
  int n = (IPSET_OPT_PROTO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PROTO) | 0);  /* check that IPSET_OPT_PROTO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_IFACE(unsigned long long *o)
{
  int n = (IPSET_OPT_IFACE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_IFACE) | 0);  /* check that IPSET_OPT_IFACE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SETNAME2(unsigned long long *o)
{
  int n = (IPSET_OPT_SETNAME2) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SETNAME2) | 0);  /* check that IPSET_OPT_SETNAME2 is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_EXIST(unsigned long long *o)
{
  int n = (IPSET_OPT_EXIST) <= 0;
  *o = (unsigned long long)((IPSET_OPT_EXIST) | 0);  /* check that IPSET_OPT_EXIST is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_BEFORE(unsigned long long *o)
{
  int n = (IPSET_OPT_BEFORE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_BEFORE) | 0);  /* check that IPSET_OPT_BEFORE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PHYSDEV(unsigned long long *o)
{
  int n = (IPSET_OPT_PHYSDEV) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PHYSDEV) | 0);  /* check that IPSET_OPT_PHYSDEV is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_NOMATCH(unsigned long long *o)
{
  int n = (IPSET_OPT_NOMATCH) <= 0;
  *o = (unsigned long long)((IPSET_OPT_NOMATCH) | 0);  /* check that IPSET_OPT_NOMATCH is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_COUNTERS(unsigned long long *o)
{
  int n = (IPSET_OPT_COUNTERS) <= 0;
  *o = (unsigned long long)((IPSET_OPT_COUNTERS) | 0);  /* check that IPSET_OPT_COUNTERS is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_PACKETS(unsigned long long *o)
{
  int n = (IPSET_OPT_PACKETS) <= 0;
  *o = (unsigned long long)((IPSET_OPT_PACKETS) | 0);  /* check that IPSET_OPT_PACKETS is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_BYTES(unsigned long long *o)
{
  int n = (IPSET_OPT_BYTES) <= 0;
  *o = (unsigned long long)((IPSET_OPT_BYTES) | 0);  /* check that IPSET_OPT_BYTES is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_CREATE_COMMENT(unsigned long long *o)
{
  int n = (IPSET_OPT_CREATE_COMMENT) <= 0;
  *o = (unsigned long long)((IPSET_OPT_CREATE_COMMENT) | 0);  /* check that IPSET_OPT_CREATE_COMMENT is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_ADT_COMMENT(unsigned long long *o)
{
  int n = (IPSET_OPT_ADT_COMMENT) <= 0;
  *o = (unsigned long long)((IPSET_OPT_ADT_COMMENT) | 0);  /* check that IPSET_OPT_ADT_COMMENT is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SKBINFO(unsigned long long *o)
{
  int n = (IPSET_OPT_SKBINFO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SKBINFO) | 0);  /* check that IPSET_OPT_SKBINFO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SKBMARK(unsigned long long *o)
{
  int n = (IPSET_OPT_SKBMARK) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SKBMARK) | 0);  /* check that IPSET_OPT_SKBMARK is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SKBPRIO(unsigned long long *o)
{
  int n = (IPSET_OPT_SKBPRIO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SKBPRIO) | 0);  /* check that IPSET_OPT_SKBPRIO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_SKBQUEUE(unsigned long long *o)
{
  int n = (IPSET_OPT_SKBQUEUE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_SKBQUEUE) | 0);  /* check that IPSET_OPT_SKBQUEUE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_FLAGS(unsigned long long *o)
{
  int n = (IPSET_OPT_FLAGS) <= 0;
  *o = (unsigned long long)((IPSET_OPT_FLAGS) | 0);  /* check that IPSET_OPT_FLAGS is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_CADT_FLAGS(unsigned long long *o)
{
  int n = (IPSET_OPT_CADT_FLAGS) <= 0;
  *o = (unsigned long long)((IPSET_OPT_CADT_FLAGS) | 0);  /* check that IPSET_OPT_CADT_FLAGS is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_ELEM(unsigned long long *o)
{
  int n = (IPSET_OPT_ELEM) <= 0;
  *o = (unsigned long long)((IPSET_OPT_ELEM) | 0);  /* check that IPSET_OPT_ELEM is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_TYPE(unsigned long long *o)
{
  int n = (IPSET_OPT_TYPE) <= 0;
  *o = (unsigned long long)((IPSET_OPT_TYPE) | 0);  /* check that IPSET_OPT_TYPE is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_LINENO(unsigned long long *o)
{
  int n = (IPSET_OPT_LINENO) <= 0;
  *o = (unsigned long long)((IPSET_OPT_LINENO) | 0);  /* check that IPSET_OPT_LINENO is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_REVISION(unsigned long long *o)
{
  int n = (IPSET_OPT_REVISION) <= 0;
  *o = (unsigned long long)((IPSET_OPT_REVISION) | 0);  /* check that IPSET_OPT_REVISION is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_REVISION_MIN(unsigned long long *o)
{
  int n = (IPSET_OPT_REVISION_MIN) <= 0;
  *o = (unsigned long long)((IPSET_OPT_REVISION_MIN) | 0);  /* check that IPSET_OPT_REVISION_MIN is an integer */
  return n;
}

static int _cffi_const_IPSET_OPT_MAX(unsigned long long *o)
{
  int n = (IPSET_OPT_MAX) <= 0;
  *o = (unsigned long long)((IPSET_OPT_MAX) | 0);  /* check that IPSET_OPT_MAX is an integer */
  return n;
}

static int _cffi_const_IPSET_LIST_NONE(unsigned long long *o)
{
  int n = (IPSET_LIST_NONE) <= 0;
  *o = (unsigned long long)((IPSET_LIST_NONE) | 0);  /* check that IPSET_LIST_NONE is an integer */
  return n;
}

static int _cffi_const_IPSET_LIST_PLAIN(unsigned long long *o)
{
  int n = (IPSET_LIST_PLAIN) <= 0;
  *o = (unsigned long long)((IPSET_LIST_PLAIN) | 0);  /* check that IPSET_LIST_PLAIN is an integer */
  return n;
}

static int _cffi_const_IPSET_LIST_SAVE(unsigned long long *o)
{
  int n = (IPSET_LIST_SAVE) <= 0;
  *o = (unsigned long long)((IPSET_LIST_SAVE) | 0);  /* check that IPSET_LIST_SAVE is an integer */
  return n;
}

static int _cffi_const_IPSET_LIST_XML(unsigned long long *o)
{
  int n = (IPSET_LIST_XML) <= 0;
  *o = (unsigned long long)((IPSET_LIST_XML) | 0);  /* check that IPSET_LIST_XML is an integer */
  return n;
}

static struct _cffi_externpy_s _cffi_externpy__out_buffer =
  { "libipset.ipset.out_buffer", (int)sizeof(int), 0, 0 };

static int out_buffer(char * a0)
{
  char a[8];
  char *p = a;
  *(char * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__out_buffer, p);
  return *(int *)p;
}

static int _cffi_d_inet_pton(int x0, char const * x1, void * x2)
{
  return inet_pton(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_inet_pton(PyObject *self, PyObject *args)
{
  int x0;
  char const * x1;
  void * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "inet_pton", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(14), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(14), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(19), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = inet_pton(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_inet_pton _cffi_d_inet_pton
#endif

static int _cffi_d_ipset_cmd(struct ipset_session * x0, enum ipset_cmd x1, uint32_t x2)
{
  return ipset_cmd(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_cmd(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_cmd x1;
  uint32_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ipset_cmd", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(31), arg1) < 0)
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint32_t);
  if (x2 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_cmd(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_cmd _cffi_d_ipset_cmd
#endif

static int _cffi_d_ipset_commit(struct ipset_session * x0)
{
  return ipset_commit(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_commit(PyObject *self, PyObject *arg0)
{
  struct ipset_session * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_commit(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_commit _cffi_d_ipset_commit
#endif

static void const * _cffi_d_ipset_data_get(struct ipset_data const * x0, enum ipset_opt x1)
{
  return ipset_data_get(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_data_get(PyObject *self, PyObject *args)
{
  struct ipset_data const * x0;
  enum ipset_opt x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  void const * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_data_get", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(82), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_data const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(82), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(23), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_data_get(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(24));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_data_get _cffi_d_ipset_data_get
#endif

static int _cffi_d_ipset_data_set(struct ipset_data * x0, enum ipset_opt x1, void const * x2)
{
  return ipset_data_set(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_data_set(PyObject *self, PyObject *args)
{
  struct ipset_data * x0;
  enum ipset_opt x1;
  void const * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ipset_data_set", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(22), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(22), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(23), arg1) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(24), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (void const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(24), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_data_set(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_data_set _cffi_d_ipset_data_set
#endif

static int _cffi_d_ipset_envopt_parse(struct ipset_session * x0, int x1, char const * x2)
{
  return ipset_envopt_parse(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_envopt_parse(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  int x1;
  char const * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ipset_envopt_parse", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(14), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(14), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_envopt_parse(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_envopt_parse _cffi_d_ipset_envopt_parse
#endif

static _Bool _cffi_d_ipset_envopt_test(struct ipset_session * x0, enum ipset_envopt x1)
{
  return ipset_envopt_test(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_envopt_test(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_envopt x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  _Bool result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_envopt_test", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(2), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_envopt_test(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c__Bool(result);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_envopt_test _cffi_d_ipset_envopt_test
#endif

static int _cffi_d_ipset_errcode(struct ipset_session * x0, enum ipset_cmd x1, int x2)
{
  return ipset_errcode(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_errcode(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_cmd x1;
  int x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ipset_errcode", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(31), arg1) < 0)
    return NULL;

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_errcode(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_errcode _cffi_d_ipset_errcode
#endif

static void _cffi_d_ipset_load_types(void)
{
  ipset_load_types();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_load_types(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ipset_load_types(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ipset_load_types _cffi_d_ipset_load_types
#endif

static int _cffi_d_ipset_parse_elem(struct ipset_session * x0, enum ipset_opt x1, char const * x2)
{
  return ipset_parse_elem(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_parse_elem(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_opt x1;
  char const * x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ipset_parse_elem", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(23), arg1) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(14), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(14), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_parse_elem(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_parse_elem _cffi_d_ipset_parse_elem
#endif

static struct ipset_type const * _cffi_d_ipset_saved_type(struct ipset_session const * x0)
{
  return ipset_saved_type(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_saved_type(PyObject *self, PyObject *arg0)
{
  struct ipset_session const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct ipset_type const * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_saved_type(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(107));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_saved_type _cffi_d_ipset_saved_type
#endif

static struct ipset_data * _cffi_d_ipset_session_data(struct ipset_session const * x0)
{
  return ipset_session_data(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_data(PyObject *self, PyObject *arg0)
{
  struct ipset_session const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct ipset_data * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_data(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(22));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_data _cffi_d_ipset_session_data
#endif

static char const * _cffi_d_ipset_session_error(struct ipset_session const * x0)
{
  return ipset_session_error(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_error(PyObject *self, PyObject *arg0)
{
  struct ipset_session const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  char const * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_error(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(14));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_error _cffi_d_ipset_session_error
#endif

static int _cffi_d_ipset_session_fini(struct ipset_session * x0)
{
  return ipset_session_fini(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_fini(PyObject *self, PyObject *arg0)
{
  struct ipset_session * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_fini(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_fini _cffi_d_ipset_session_fini
#endif

static struct ipset_handle * _cffi_d_ipset_session_handle(struct ipset_session const * x0)
{
  return ipset_session_handle(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_handle(PyObject *self, PyObject *arg0)
{
  struct ipset_session const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct ipset_handle * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_handle(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(104));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_handle _cffi_d_ipset_session_handle
#endif

static struct ipset_session * _cffi_d_ipset_session_init(int(* x0)(char const *, ...))
{
  return ipset_session_init(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_init(PyObject *self, PyObject *arg0)
{
  int(* x0)(char const *, ...);
  struct ipset_session * result;
  PyObject *pyresult;

  x0 = (int(*)(char const *, ...))_cffi_to_c_pointer(arg0, _cffi_type(55));
  if (x0 == (int(*)(char const *, ...))NULL && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_init(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_init _cffi_d_ipset_session_init
#endif

static void _cffi_d_ipset_session_lineno(struct ipset_session * x0, uint32_t x1)
{
  ipset_session_lineno(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_lineno(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  uint32_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_session_lineno", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint32_t);
  if (x1 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ipset_session_lineno(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ipset_session_lineno _cffi_d_ipset_session_lineno
#endif

static int _cffi_d_ipset_session_outfn(struct ipset_session * x0, int(* x1)(char const *, ...))
{
  return ipset_session_outfn(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_outfn(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  int(* x1)(char const *, ...);
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_session_outfn", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (int(*)(char const *, ...))_cffi_to_c_pointer(arg1, _cffi_type(55));
  if (x1 == (int(*)(char const *, ...))NULL && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_outfn(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_outfn _cffi_d_ipset_session_outfn
#endif

static int _cffi_d_ipset_session_output(struct ipset_session * x0, enum ipset_output_mode x1)
{
  return ipset_session_output(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_output(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_output_mode x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_session_output", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(51), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_output(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_output _cffi_d_ipset_session_output
#endif

static void _cffi_const_ipset_session_report(char *o)
{
  *(int(* *)(struct ipset_session *, enum ipset_err_type, char const *, ...))o = ipset_session_report;
}

static void _cffi_d_ipset_session_report_reset(struct ipset_session * x0)
{
  ipset_session_report_reset(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_report_reset(PyObject *self, PyObject *arg0)
{
  struct ipset_session * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ipset_session_report_reset(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ipset_session_report_reset _cffi_d_ipset_session_report_reset
#endif

static char const * _cffi_d_ipset_session_warning(struct ipset_session const * x0)
{
  return ipset_session_warning(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_session_warning(PyObject *self, PyObject *arg0)
{
  struct ipset_session const * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  char const * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_session_warning(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(14));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_session_warning _cffi_d_ipset_session_warning
#endif

static struct ipset_type const * _cffi_d_ipset_type_check(struct ipset_session * x0)
{
  return ipset_type_check(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_type_check(PyObject *self, PyObject *arg0)
{
  struct ipset_session * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct ipset_type const * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_type_check(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(107));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_type_check _cffi_d_ipset_type_check
#endif

static struct ipset_type const * _cffi_d_ipset_type_get(struct ipset_session * x0, enum ipset_cmd x1)
{
  return ipset_type_get(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ipset_type_get(PyObject *self, PyObject *args)
{
  struct ipset_session * x0;
  enum ipset_cmd x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct ipset_type const * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ipset_type_get", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct ipset_session *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  if (_cffi_to_c((char *)&x1, _cffi_type(31), arg1) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ipset_type_get(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(107));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_ipset_type_get _cffi_d_ipset_type_get
#endif

static void _cffi_const_out_fn(char *o)
{
  *(int(* *)(char *, ...))o = out_fn;
}

static void _cffi_const_printf(char *o)
{
  *(int(* *)(char const *, ...))o = printf;
}

static int _cffi_const_AF_INET(unsigned long long *o)
{
  int n = (AF_INET) <= 0;
  *o = (unsigned long long)((AF_INET) | 0);  /* check that AF_INET is an integer */
  if (!_cffi_check_int(*o, n, 2U))
    n |= 2;
  return n;
}

static int _cffi_const_AF_INET6(unsigned long long *o)
{
  int n = (AF_INET6) <= 0;
  *o = (unsigned long long)((AF_INET6) | 0);  /* check that AF_INET6 is an integer */
  if (!_cffi_check_int(*o, n, 10U))
    n |= 2;
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_in6_addr(struct in6_addr *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  /* cannot generate 'union $2' in field '__in6_u': unknown type name */
}
struct _cffi_align_struct_in6_addr { char x; struct in6_addr y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_in_addr(struct in_addr *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->s_addr) | 0);  /* check that 'struct in_addr.s_addr' is an integer */
}
struct _cffi_align_struct_in_addr { char x; struct in_addr y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_ipset_errcode_table(struct ipset_errcode_table *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->errcode) | 0);  /* check that 'struct ipset_errcode_table.errcode' is an integer */
  { enum ipset_cmd *tmp = &p->cmd; (void)tmp; }
  { char const * *tmp = &p->message; (void)tmp; }
}
struct _cffi_align_struct_ipset_errcode_table { char x; struct ipset_errcode_table y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_union_nf_inet_addr(union nf_inet_addr *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { uint32_t(*tmp)[4] = &p->all; (void)tmp; }
  (void)((p->ip) | 0);  /* check that 'union nf_inet_addr.ip' is an integer */
  { uint32_t(*tmp)[4] = &p->ip6; (void)tmp; }
  { struct in_addr *tmp = &p->in; (void)tmp; }
  { struct in6_addr *tmp = &p->in6; (void)tmp; }
}
struct _cffi_align_union_nf_inet_addr { char x; union nf_inet_addr y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "AF_INET", (void *)_cffi_const_AF_INET, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "AF_INET6", (void *)_cffi_const_AF_INET6, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "IPSET_CMD_ADD", (void *)_cffi_const_IPSET_CMD_ADD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_COMMIT", (void *)_cffi_const_IPSET_CMD_COMMIT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_CREATE", (void *)_cffi_const_IPSET_CMD_CREATE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_DEL", (void *)_cffi_const_IPSET_CMD_DEL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_DESTROY", (void *)_cffi_const_IPSET_CMD_DESTROY, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_FLUSH", (void *)_cffi_const_IPSET_CMD_FLUSH, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_HEADER", (void *)_cffi_const_IPSET_CMD_HEADER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_HELP", (void *)_cffi_const_IPSET_CMD_HELP, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_LIST", (void *)_cffi_const_IPSET_CMD_LIST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_MAX", (void *)_cffi_const_IPSET_CMD_MAX, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_NONE", (void *)_cffi_const_IPSET_CMD_NONE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_PROTOCOL", (void *)_cffi_const_IPSET_CMD_PROTOCOL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_QUIT", (void *)_cffi_const_IPSET_CMD_QUIT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_RENAME", (void *)_cffi_const_IPSET_CMD_RENAME, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_RESTORE", (void *)_cffi_const_IPSET_CMD_RESTORE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_SAVE", (void *)_cffi_const_IPSET_CMD_SAVE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_SWAP", (void *)_cffi_const_IPSET_CMD_SWAP, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_TEST", (void *)_cffi_const_IPSET_CMD_TEST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_TYPE", (void *)_cffi_const_IPSET_CMD_TYPE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_CMD_VERSION", (void *)_cffi_const_IPSET_CMD_VERSION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_EXIST", (void *)_cffi_const_IPSET_ENV_EXIST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_LIST_HEADER", (void *)_cffi_const_IPSET_ENV_LIST_HEADER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_LIST_SETNAME", (void *)_cffi_const_IPSET_ENV_LIST_SETNAME, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_QUIET", (void *)_cffi_const_IPSET_ENV_QUIET, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_RESOLVE", (void *)_cffi_const_IPSET_ENV_RESOLVE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ENV_SORTED", (void *)_cffi_const_IPSET_ENV_SORTED, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_ERROR", (void *)_cffi_const_IPSET_ERROR, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_LIST_NONE", (void *)_cffi_const_IPSET_LIST_NONE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_LIST_PLAIN", (void *)_cffi_const_IPSET_LIST_PLAIN, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_LIST_SAVE", (void *)_cffi_const_IPSET_LIST_SAVE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_LIST_XML", (void *)_cffi_const_IPSET_LIST_XML, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_MSG_MAX", (void *)_cffi_const_IPSET_MSG_MAX, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_ADT_COMMENT", (void *)_cffi_const_IPSET_OPT_ADT_COMMENT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_BEFORE", (void *)_cffi_const_IPSET_OPT_BEFORE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_BYTES", (void *)_cffi_const_IPSET_OPT_BYTES, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_CADT_FLAGS", (void *)_cffi_const_IPSET_OPT_CADT_FLAGS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_CIDR", (void *)_cffi_const_IPSET_OPT_CIDR, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_CIDR2", (void *)_cffi_const_IPSET_OPT_CIDR2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_COUNTERS", (void *)_cffi_const_IPSET_OPT_COUNTERS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_CREATE_COMMENT", (void *)_cffi_const_IPSET_OPT_CREATE_COMMENT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_ELEM", (void *)_cffi_const_IPSET_OPT_ELEM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_ELEMENTS", (void *)_cffi_const_IPSET_OPT_ELEMENTS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_ETHER", (void *)_cffi_const_IPSET_OPT_ETHER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_EXIST", (void *)_cffi_const_IPSET_OPT_EXIST, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_FAMILY", (void *)_cffi_const_IPSET_OPT_FAMILY, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_FLAGS", (void *)_cffi_const_IPSET_OPT_FLAGS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_FORCEADD", (void *)_cffi_const_IPSET_OPT_FORCEADD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_GC", (void *)_cffi_const_IPSET_OPT_GC, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_HASHSIZE", (void *)_cffi_const_IPSET_OPT_HASHSIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IFACE", (void *)_cffi_const_IPSET_OPT_IFACE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IP", (void *)_cffi_const_IPSET_OPT_IP, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IP2", (void *)_cffi_const_IPSET_OPT_IP2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IP2_TO", (void *)_cffi_const_IPSET_OPT_IP2_TO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IP_FROM", (void *)_cffi_const_IPSET_OPT_IP_FROM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_IP_TO", (void *)_cffi_const_IPSET_OPT_IP_TO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_LINENO", (void *)_cffi_const_IPSET_OPT_LINENO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_MARK", (void *)_cffi_const_IPSET_OPT_MARK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_MARKMASK", (void *)_cffi_const_IPSET_OPT_MARKMASK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_MAX", (void *)_cffi_const_IPSET_OPT_MAX, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_MAXELEM", (void *)_cffi_const_IPSET_OPT_MAXELEM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_MEMSIZE", (void *)_cffi_const_IPSET_OPT_MEMSIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_NAME", (void *)_cffi_const_IPSET_OPT_NAME, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_NAMEREF", (void *)_cffi_const_IPSET_OPT_NAMEREF, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_NETMASK", (void *)_cffi_const_IPSET_OPT_NETMASK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_NOMATCH", (void *)_cffi_const_IPSET_OPT_NOMATCH, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_NONE", (void *)_cffi_const_IPSET_OPT_NONE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PACKETS", (void *)_cffi_const_IPSET_OPT_PACKETS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PHYSDEV", (void *)_cffi_const_IPSET_OPT_PHYSDEV, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PORT", (void *)_cffi_const_IPSET_OPT_PORT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PORT_FROM", (void *)_cffi_const_IPSET_OPT_PORT_FROM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PORT_TO", (void *)_cffi_const_IPSET_OPT_PORT_TO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PROBES", (void *)_cffi_const_IPSET_OPT_PROBES, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_PROTO", (void *)_cffi_const_IPSET_OPT_PROTO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_REFERENCES", (void *)_cffi_const_IPSET_OPT_REFERENCES, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_RESIZE", (void *)_cffi_const_IPSET_OPT_RESIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_REVISION", (void *)_cffi_const_IPSET_OPT_REVISION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_REVISION_MIN", (void *)_cffi_const_IPSET_OPT_REVISION_MIN, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SETNAME2", (void *)_cffi_const_IPSET_OPT_SETNAME2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SIZE", (void *)_cffi_const_IPSET_OPT_SIZE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SKBINFO", (void *)_cffi_const_IPSET_OPT_SKBINFO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SKBMARK", (void *)_cffi_const_IPSET_OPT_SKBMARK, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SKBPRIO", (void *)_cffi_const_IPSET_OPT_SKBPRIO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_SKBQUEUE", (void *)_cffi_const_IPSET_OPT_SKBQUEUE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_TIMEOUT", (void *)_cffi_const_IPSET_OPT_TIMEOUT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_TYPE", (void *)_cffi_const_IPSET_OPT_TYPE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_OPT_TYPENAME", (void *)_cffi_const_IPSET_OPT_TYPENAME, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_SETNAME", (void *)_cffi_const_IPSET_SETNAME, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "IPSET_WARNING", (void *)_cffi_const_IPSET_WARNING, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_ARP", (void *)_cffi_const_NFPROTO_ARP, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_BRIDGE", (void *)_cffi_const_NFPROTO_BRIDGE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_DECNET", (void *)_cffi_const_NFPROTO_DECNET, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_IPV4", (void *)_cffi_const_NFPROTO_IPV4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_IPV6", (void *)_cffi_const_NFPROTO_IPV6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_NUMPROTO", (void *)_cffi_const_NFPROTO_NUMPROTO, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "NFPROTO_UNSPEC", (void *)_cffi_const_NFPROTO_UNSPEC, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "inet_pton", (void *)_cffi_f_inet_pton, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 16), (void *)_cffi_d_inet_pton },
  { "ipset_cmd", (void *)_cffi_f_ipset_cmd, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 34), (void *)_cffi_d_ipset_cmd },
  { "ipset_commit", (void *)_cffi_f_ipset_commit, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 26), (void *)_cffi_d_ipset_commit },
  { "ipset_data_get", (void *)_cffi_f_ipset_data_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 81), (void *)_cffi_d_ipset_data_get },
  { "ipset_data_set", (void *)_cffi_f_ipset_data_set, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_ipset_data_set },
  { "ipset_envopt_parse", (void *)_cffi_f_ipset_envopt_parse, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 57), (void *)_cffi_d_ipset_envopt_parse },
  { "ipset_envopt_test", (void *)_cffi_f_ipset_envopt_test, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_ipset_envopt_test },
  { "ipset_errcode", (void *)_cffi_f_ipset_errcode, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_ipset_errcode },
  { "ipset_load_types", (void *)_cffi_f_ipset_load_types, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 92), (void *)_cffi_d_ipset_load_types },
  { "ipset_parse_elem", (void *)_cffi_f_ipset_parse_elem, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 44), (void *)_cffi_d_ipset_parse_elem },
  { "ipset_saved_type", (void *)_cffi_f_ipset_saved_type, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 78), (void *)_cffi_d_ipset_saved_type },
  { "ipset_session_data", (void *)_cffi_f_ipset_session_data, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 62), (void *)_cffi_d_ipset_session_data },
  { "ipset_session_error", (void *)_cffi_f_ipset_session_error, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 4), (void *)_cffi_d_ipset_session_error },
  { "ipset_session_fini", (void *)_cffi_f_ipset_session_fini, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 26), (void *)_cffi_d_ipset_session_fini },
  { "ipset_session_handle", (void *)_cffi_f_ipset_session_handle, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 65), (void *)_cffi_d_ipset_session_handle },
  { "ipset_session_init", (void *)_cffi_f_ipset_session_init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 68), (void *)_cffi_d_ipset_session_init },
  { "ipset_session_lineno", (void *)_cffi_f_ipset_session_lineno, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 88), (void *)_cffi_d_ipset_session_lineno },
  { "ipset_session_outfn", (void *)_cffi_f_ipset_session_outfn, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 53), (void *)_cffi_d_ipset_session_outfn },
  { "ipset_session_output", (void *)_cffi_f_ipset_session_output, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 49), (void *)_cffi_d_ipset_session_output },
  { "ipset_session_report", (void *)_cffi_const_ipset_session_report, _CFFI_OP(_CFFI_OP_CONSTANT, 99), (void *)0 },
  { "ipset_session_report_reset", (void *)_cffi_f_ipset_session_report_reset, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 85), (void *)_cffi_d_ipset_session_report_reset },
  { "ipset_session_warning", (void *)_cffi_f_ipset_session_warning, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 4), (void *)_cffi_d_ipset_session_warning },
  { "ipset_type_check", (void *)_cffi_f_ipset_type_check, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 71), (void *)_cffi_d_ipset_type_check },
  { "ipset_type_get", (void *)_cffi_f_ipset_type_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 74), (void *)_cffi_d_ipset_type_get },
  { "out_buffer", (void *)&_cffi_externpy__out_buffer, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 97), (void *)out_buffer },
  { "out_fn", (void *)_cffi_const_out_fn, _CFFI_OP(_CFFI_OP_CONSTANT, 98), (void *)0 },
  { "printf", (void *)_cffi_const_printf, _CFFI_OP(_CFFI_OP_CONSTANT, 55), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "__in6_u", offsetof(struct in6_addr, __in6_u),
               sizeof(((struct in6_addr *)0)->__in6_u),
               _CFFI_OP(_CFFI_OP_NOOP, 117) },
  { "s_addr", offsetof(struct in_addr, s_addr),
              sizeof(((struct in_addr *)0)->s_addr),
              _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "errcode", offsetof(struct ipset_errcode_table, errcode),
               sizeof(((struct ipset_errcode_table *)0)->errcode),
               _CFFI_OP(_CFFI_OP_NOOP, 17) },
  { "cmd", offsetof(struct ipset_errcode_table, cmd),
           sizeof(((struct ipset_errcode_table *)0)->cmd),
           _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "message", offsetof(struct ipset_errcode_table, message),
               sizeof(((struct ipset_errcode_table *)0)->message),
               _CFFI_OP(_CFFI_OP_NOOP, 14) },
  { "all", offsetof(union nf_inet_addr, all),
           sizeof(((union nf_inet_addr *)0)->all),
           _CFFI_OP(_CFFI_OP_NOOP, 112) },
  { "ip", offsetof(union nf_inet_addr, ip),
          sizeof(((union nf_inet_addr *)0)->ip),
          _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "ip6", offsetof(union nf_inet_addr, ip6),
           sizeof(((union nf_inet_addr *)0)->ip6),
           _CFFI_OP(_CFFI_OP_NOOP, 112) },
  { "in", offsetof(union nf_inet_addr, in),
          sizeof(((union nf_inet_addr *)0)->in),
          _CFFI_OP(_CFFI_OP_NOOP, 101) },
  { "in6", offsetof(union nf_inet_addr, in6),
           sizeof(((union nf_inet_addr *)0)->in6),
           _CFFI_OP(_CFFI_OP_NOOP, 100) },
  { "__u6_addr8", (size_t)-1,
                  (size_t)-1,
                  _CFFI_OP(_CFFI_OP_NOOP, 115) },
  { "__u6_addr16", (size_t)-1,
                   (size_t)-1,
                   _CFFI_OP(_CFFI_OP_NOOP, 110) },
  { "__u6_addr32", (size_t)-1,
                   (size_t)-1,
                   _CFFI_OP(_CFFI_OP_NOOP, 112) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$2", 117, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 10, 3 /* unnamed */ },
  { "in6_addr", 100, _CFFI_F_CHECK_FIELDS,
    sizeof(struct in6_addr), offsetof(struct _cffi_align_struct_in6_addr, y), 0, 1 },
  { "in_addr", 101, _CFFI_F_CHECK_FIELDS,
    sizeof(struct in_addr), offsetof(struct _cffi_align_struct_in_addr, y), 1, 1 },
  { "ipset_data", 102, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ipset_errcode_table", 103, _CFFI_F_CHECK_FIELDS,
    sizeof(struct ipset_errcode_table), offsetof(struct _cffi_align_struct_ipset_errcode_table, y), 2, 3 },
  { "ipset_handle", 105, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ipset_session", 106, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ipset_type", 108, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "nf_inet_addr", 118, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    sizeof(union nf_inet_addr), offsetof(struct _cffi_align_union_nf_inet_addr, y), 5, 5 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$1", 96, _cffi_prim_int(4, 0),
    "NFPROTO_UNSPEC,NFPROTO_IPV4,NFPROTO_ARP,NFPROTO_BRIDGE,NFPROTO_IPV6,NFPROTO_DECNET,NFPROTO_NUMPROTO" },
  { "ipset_cmd", 31, _cffi_prim_int(sizeof(enum ipset_cmd), ((enum ipset_cmd)-1) <= 0),
    "IPSET_CMD_NONE,IPSET_CMD_PROTOCOL,IPSET_CMD_CREATE,IPSET_CMD_DESTROY,IPSET_CMD_FLUSH,IPSET_CMD_RENAME,IPSET_CMD_SWAP,IPSET_CMD_LIST,IPSET_CMD_SAVE,IPSET_CMD_ADD,IPSET_CMD_DEL,IPSET_CMD_TEST,IPSET_CMD_HEADER,IPSET_CMD_TYPE,IPSET_MSG_MAX,IPSET_CMD_RESTORE,IPSET_CMD_HELP,IPSET_CMD_VERSION,IPSET_CMD_QUIT,IPSET_CMD_MAX,IPSET_CMD_COMMIT" },
  { "ipset_envopt", 2, _cffi_prim_int(sizeof(enum ipset_envopt), ((enum ipset_envopt)-1) <= 0),
    "IPSET_ENV_SORTED,IPSET_ENV_QUIET,IPSET_ENV_RESOLVE,IPSET_ENV_EXIST,IPSET_ENV_LIST_SETNAME,IPSET_ENV_LIST_HEADER" },
  { "ipset_err_type", 41, _cffi_prim_int(sizeof(enum ipset_err_type), ((enum ipset_err_type)-1) <= 0),
    "IPSET_ERROR,IPSET_WARNING" },
  { "ipset_opt", 23, _cffi_prim_int(sizeof(enum ipset_opt), ((enum ipset_opt)-1) <= 0),
    "IPSET_OPT_NONE,IPSET_SETNAME,IPSET_OPT_TYPENAME,IPSET_OPT_FAMILY,IPSET_OPT_IP,IPSET_OPT_IP_FROM,IPSET_OPT_IP_TO,IPSET_OPT_CIDR,IPSET_OPT_MARK,IPSET_OPT_PORT,IPSET_OPT_PORT_FROM,IPSET_OPT_PORT_TO,IPSET_OPT_TIMEOUT,IPSET_OPT_GC,IPSET_OPT_HASHSIZE,IPSET_OPT_MAXELEM,IPSET_OPT_MARKMASK,IPSET_OPT_NETMASK,IPSET_OPT_PROBES,IPSET_OPT_RESIZE,IPSET_OPT_SIZE,IPSET_OPT_FORCEADD,IPSET_OPT_ELEMENTS,IPSET_OPT_REFERENCES,IPSET_OPT_MEMSIZE,IPSET_OPT_ETHER,IPSET_OPT_NAME,IPSET_OPT_NAMEREF,IPSET_OPT_IP2,IPSET_OPT_CIDR2,IPSET_OPT_IP2_TO,IPSET_OPT_PROTO,IPSET_OPT_IFACE,IPSET_OPT_SETNAME2,IPSET_OPT_EXIST,IPSET_OPT_BEFORE,IPSET_OPT_PHYSDEV,IPSET_OPT_NOMATCH,IPSET_OPT_COUNTERS,IPSET_OPT_PACKETS,IPSET_OPT_BYTES,IPSET_OPT_CREATE_COMMENT,IPSET_OPT_ADT_COMMENT,IPSET_OPT_SKBINFO,IPSET_OPT_SKBMARK,IPSET_OPT_SKBPRIO,IPSET_OPT_SKBQUEUE,IPSET_OPT_FLAGS,IPSET_OPT_CADT_FLAGS,IPSET_OPT_ELEM,IPSET_OPT_TYPE,IPSET_OPT_LINENO,IPSET_OPT_REVISION,IPSET_OPT_REVISION_MIN,IPSET_OPT_MAX" },
  { "ipset_output_mode", 51, _cffi_prim_int(sizeof(enum ipset_output_mode), ((enum ipset_output_mode)-1) <= 0),
    "IPSET_LIST_NONE,IPSET_LIST_PLAIN,IPSET_LIST_SAVE,IPSET_LIST_XML" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "in_addr_t", 37 },
  { "ipset_outfn", 55 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  124,  /* num_globals */
  9,  /* num_struct_unions */
  6,  /* num_enums */
  2,  /* num_typenames */
  NULL,  /* no includes */
  120,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_ipset(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_ipset(void) { return NULL; }
#  else
     initipset(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_ipset(void)
{
  return _cffi_init("libipset.ipset", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initipset(void)
{
  _cffi_init("libipset.ipset", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
